/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../assets/small_portal.glb --transform --shadows 
Files: ../assets/small_portal.glb [1.21MB] > small_portal-transformed.glb [197.26KB] (84%)
Author: DAVID.3D.ART (https://sketchfab.com/david3dart)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/button-from-portal-2-original-f1c4fcfc668a4577a30f4d1c8ed3ca9a
Title: Button - from portal 2 (original)
*/

import { useGLTF } from '@react-three/drei'
import { CylinderCollider, RigidBody } from '@react-three/rapier'

export function SmallPortal(props) {
  const { nodes, materials } = useGLTF('models/small_portal-transformed.glb')
  return (
    <RigidBody colliders={false} type='fixed' onIntersectionEnter={() => props.hitPortal()} position={[5, 0, 0]}>
      <group {...props} dispose={null} scale={0.8}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.portal_button_switch} skeleton={nodes.Object_8.skeleton} scale={0.02} />
        <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.portal_button_blue} skeleton={nodes.Object_9.skeleton} scale={0.02} />
      </group>
      <CylinderCollider args={[0.25, 0.9]} position={[0, 0, 0]} sensor />
    </RigidBody>
  )
}

useGLTF.preload('models/small_portal-transformed.glb')
