/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../assets/Labs.glb --transform --shadows --keepgroups 
Files: ../assets/Labs.glb [6.36MB] > Labs-transformed.glb [687.8KB] (89%)
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Labs(props) {
  const { nodes, materials } = useGLTF('models/Labs-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders="trimesh" type='fixed'>
        <group>
          <group position={[10.904, 0.3, -3.486]}>
            <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials.Plastic} />
            <mesh castShadow receiveShadow geometry={nodes.Cube013_1.geometry} material={materials['ceramic room']} />
          </group>
          <group position={[3.793, 2.485, -3.539]}>
            <mesh castShadow receiveShadow geometry={nodes.Cube033.geometry} material={materials.Plastic} />
            <mesh castShadow receiveShadow geometry={nodes.Cube033_1.geometry} material={materials['ceramic room']} />
          </group>
        </group>
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/Labs-transformed.glb')
