/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../assets/Labter.glb --transform --shadows --keepgroups 
Files: ../assets/Labter.glb [19.21MB] > Labter-transformed.glb [3.79MB] (80%)
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Labter(props) {
  const { nodes, materials } = useGLTF('models/Labter-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <RigidBody colliders="trimesh" type="fixed">
          <group>
            <mesh castShadow receiveShadow geometry={nodes.Cube006.geometry} material={materials['labter-floor']} />
            <mesh castShadow receiveShadow geometry={nodes.Cube006_1.geometry} material={materials['White Wall 02-Freepoly.org']} />
            <mesh castShadow receiveShadow geometry={nodes.Cube006_2.geometry} material={materials.Plastic} />
          </group>
          <mesh castShadow receiveShadow geometry={nodes['lab-kalterisasi'].geometry} material={materials.Plastic} position={[-11.756, 0.3, -3.882]} />
          <group position={[-13.028, 0.15, -0.605]}>
            <mesh castShadow receiveShadow geometry={nodes.Cube004.geometry} material={materials['White Wall 02-Freepoly.org']} />
            <mesh castShadow receiveShadow geometry={nodes.Cube004_1.geometry} material={materials.clean_pebbles} />
          </group>
        </RigidBody>
      </group>
    </group>
  )
}

useGLTF.preload('models/Labter-transformed.glb')
