/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/feri/Downloads/portal.glb --shadows 
Author: N1x (https://sketchfab.com/N1x)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-portal-38e1dec9d32d4a768f8e810848b7b59b
Title: Low Poly Portal
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { CuboidCollider, RigidBody } from '@react-three/rapier'

export function Portal(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/portal.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['Animation'].repetitions = 1
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <RigidBody colliders={false} type="fixed">
            <group name="root" onClick={() => { actions['Animation'].play() }}>
              <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]} scale={0.5}>
                <group name="Door_7" position={[2.042, 2.881, -0.12]}>
                  <mesh name="Object_17" castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials.Base} />
                  <mesh name="Object_18" castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials.EMyELLOW} />
                </group>
                <group name="Plane001_19" position={[0.284, 3.238, -0.097]}>
                  <mesh name="Object_43" castShadow receiveShadow geometry={nodes.Object_43.geometry} material={materials.EMyELLOW} />
                </group>
                <group name="Cube_0" position={[0, 1, 0]}>
                  <mesh name="Object_4" castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.Base} />
                </group>
                <group name="Cube001_1" position={[2, 1.302, 0]}>
                  <mesh name="Object_6" castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.Base} />
                </group>
                <group name="Cube002_2" position={[0, 6.132, 0.526]}>
                  <mesh name="Object_8" castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.Base} />
                </group>
                <group name="Cube005_3" position={[-1.572, 2.986, 0.611]} rotation={[0, Math.PI / 9, 0]}>
                  <mesh name="Object_10" castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.Base} />
                </group>
                <group name="Circle_4" position={[0, 0.302, 0]}>
                  <mesh name="Object_12" castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.Base} />
                </group>
                <group name="Cube009_6" position={[2, 1.302, 0]}>
                  <mesh name="Object_14" castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials.Base} />
                  <mesh name="Object_15" castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials.material} />
                </group>
                <group name="Cube011_8" position={[2.079, 3.158, 0.455]} rotation={[-0.262, 0, 0]}>
                  <mesh name="Object_20" castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials.Base} />
                </group>
                <group name="Cube012_9" position={[-2.208, 3.164, -0.463]}>
                  <mesh name="Object_22" castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials.Base} />
                </group>
                <group name="Circle002_10" position={[-1.935, 3.408, 0.612]} scale={[1.185, 1, 1.185]}>
                  <mesh name="Object_24" castShadow receiveShadow geometry={nodes.Object_24.geometry} material={materials.Base} />
                  <mesh name="Object_25" castShadow receiveShadow geometry={nodes.Object_25.geometry} material={materials.EMGreen} />
                </group>
                <group name="Circle004_11" position={[-2.13, 3.203, 0.612]} scale={[1.185, 1, 1.185]}>
                  <mesh name="Object_27" castShadow receiveShadow geometry={nodes.Object_27.geometry} material={materials.Base} />
                  <mesh name="Object_28" castShadow receiveShadow geometry={nodes.Object_28.geometry} material={materials.EMGreen} />
                </group>
                <group name="Cube015_12" position={[0.308, 6.23, 0.527]}>
                  <mesh name="Object_30" castShadow receiveShadow geometry={nodes.Object_30.geometry} material={materials.Base} />
                </group>
                <group name="Cube016_13" position={[0.308, 6.23, 0.527]}>
                  <mesh name="Object_32" castShadow receiveShadow geometry={nodes.Object_32.geometry} material={materials.Base} />
                  <mesh name="Object_33" castShadow receiveShadow geometry={nodes.Object_33.geometry} material={materials.material} />
                </group>
                <group name="Cube017_14" position={[0.305, 6.042, 0.532]}>
                  <mesh name="Object_35" castShadow receiveShadow geometry={nodes.Object_35.geometry} material={materials.material} />
                </group>
                <group name="Cube018_16" position={[2.063, 3.309, 0.576]} rotation={[-0.186, 0, 0]}>
                  <mesh name="Object_37" castShadow receiveShadow geometry={nodes.Object_37.geometry} material={materials.EMRed} />
                </group>
                <group name="Cube019_17" position={[2.072, 3.193, 0.61]} rotation={[-0.446, 0, 0]}>
                  <mesh name="Object_39" castShadow receiveShadow geometry={nodes.Object_39.geometry} material={materials.EMRed} />
                </group>
                <group name="Cube020_18" position={[-1.557, 4.425, 0.112]} rotation={[-0.081, 0.41, 0]}>
                  <mesh name="Object_41" castShadow receiveShadow geometry={nodes.Object_41.geometry} material={materials.EMBlue} />
                </group>
              </group>
            </group>
            <CuboidCollider args={[0.4, 0.4, 1]} position={[-1, 0, 1.2]} />
            <CuboidCollider args={[0.35, 0.35, 1]} position={[1.1, 0, 1.2]} />
          </RigidBody>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/portal.glb')
