/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /home/TA/resource/Laboratory/Stair.glb --transform --shadows 
Files: /home/TA/resource/Laboratory/Stair.glb [4.44MB] > Stair-transformed.glb [570.68KB] (87%)
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Stair(props) {
  const { nodes, materials } = useGLTF('models/Stair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders="trimesh" type="fixed" rotation-y={Math.PI/2}>
        <group position={[-1, 0.82, -1]} rotation={[Math.PI, 0, Math.PI]} scale={0.3}>
          <mesh castShadow receiveShadow geometry={nodes.Cube011.geometry} material={materials['White Tiles Marble PBR Texture Seamless.001']} />
          <mesh castShadow receiveShadow geometry={nodes.Cube011_1.geometry} material={materials.Plastic} />
        </group>
      </RigidBody>
    </group>
  )
}

useGLTF.preload('models/Stair-transformed.glb')
