/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../assets/TV.glb --transform --shadows 
Files: ../assets/TV.glb [4.53MB] > TV-transformed.glb [896.36KB] (80%)
*/

import { useGLTF } from '@react-three/drei'

export function SmartTV(props) {
  const { nodes, materials } = useGLTF('models/TV-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[10.339, 3.861, 5.718]} scale={0.418}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials['TV - Plastic Rough']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder_1.geometry} material={materials['TV - Screen']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder_2.geometry} material={materials['TV - Metal Brushed']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder_3.geometry} material={materials['TV - Goldy']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.drawer.geometry} material={materials['CC0Textures/Wood029/2K-JPG']} position={[10.339, 3.827, 5.718]} rotation={[-Math.PI / 2, 1.571, 0]} scale={[0.422, 0.427, 0.427]} />
      <mesh castShadow receiveShadow geometry={nodes.frame.geometry} material={materials.gloss} position={[10.339, 3.827, 5.718]} rotation={[0, 0, -Math.PI / 2]} scale={0.427} />
    </group>
  )
}

useGLTF.preload('models/TV-transformed.glb')
