/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 /home/TA/resource/Door.glb --transform --shadows --keepgroups 
Files: /home/TA/resource/Door.glb [30.91MB] > Door-transformed.glb [2.54MB] (92%)
*/

import { useGLTF } from '@react-three/drei'

export function Door(props) {
  const { nodes, materials } = useGLTF('models/Door-transformed.glb')
  return (
    <group {...props} dispose={null} key={props.key}>
      <group>
        <group position={[...props.location]}>
          <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials['Afromosia Fine Wood']} />
          <mesh castShadow receiveShadow geometry={nodes.Cube003_1.geometry} material={materials.Glass} />
          <mesh castShadow receiveShadow geometry={nodes.Cube003_2.geometry} material={materials.Handle_Metal} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/Door-transformed.glb')
