/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 /home/TA/resource/Lab.glb --transform --shadows 
Files: /home/TA/resource/Lab.glb [5.08MB] > Lab-transformed.glb [602.31KB] (88%)
*/

import { useGLTF } from '@react-three/drei'

export function Labs(props) {
  const { nodes, materials } = useGLTF('models/Lab-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[10.904, 0, -3.486]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials.Plastic} />
        <mesh castShadow receiveShadow geometry={nodes.Cube013_1.geometry} material={materials['ceramic room']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Lab-transformed.glb')
