/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ../../Blender/computer.glb --transform --shadows
Author: UROD Engine (https://sketchfab.com/Starven38)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/personal-computer-aa398650fe6e4baa8771c71266d842f4
Title: Personal Computer
*/

import { useState } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import { Interactive } from '@react-three/xr'

export function Computer(props) {
  const { nodes, materials } = useGLTF('models/computer-transformed.glb')

  const [pause, setPause] = useState(false)

  const screen = useVideoTexture(`/video/${pause ? "ICON_VERSION1_1.mp4" : "ICON_VERSION9.mp4"}`, { loop: true })
  return (
    <group {...props} dispose={null} onClick={() => setPause(!pause)}>
      <Interactive onSelect={() => setPause(!pause)}>
        <mesh castShadow receiveShadow geometry={nodes.Cube_PC_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.288} />
        <mesh castShadow receiveShadow geometry={nodes.Cube_LightMat_0.geometry} material={materials.LightMat} rotation={[-Math.PI / 2, 0, 0]} scale={0.288} />
        <mesh castShadow receiveShadow geometry={nodes.Cube_Screen_0.geometry} rotation={[-Math.PI / 2, 0, 0]} scale={0.288}>
          <meshStandardMaterial map={screen} attach="material" />
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.Cube_Keyboard_0.geometry} material={materials.Keyboard} rotation={[-Math.PI / 2, 0, 0]} scale={0.288} />
      </Interactive>
    </group>
  )
}

useGLTF.preload('models/computer-transformed.glb')