/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 /home/feri/Downloads/room.glb --transform --shadows 
Files: /home/feri/Downloads/room.glb [25.32MB] > room-transformed.glb [1.13MB] (96%)
Author: Kommander Karl (https://sketchfab.com/kommanderkarl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-themed-show-room-updated-34d8af8edce744b28d244a18ff49318a
Title: Modern Themed Show Room (Updated)
*/

import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('models/room-transformed.glb')
  return (
    <group {...props} dispose={null} scale={0.01}>
      <mesh castShadow receiveShadow geometry={nodes.WoodWall_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={48.593} />
      <mesh castShadow receiveShadow geometry={nodes.Wall2_Walls_0.geometry} material={materials.Walls} rotation={[-Math.PI / 2, 0, 0]} scale={48.593} />
      <mesh castShadow receiveShadow geometry={nodes.WindowCill_Material006_0.geometry} material={materials['Material.006']} rotation={[-Math.PI / 2, 0, 0]} scale={48.593} />
      <mesh castShadow receiveShadow geometry={nodes.Ceiling_Ceiling_0.geometry} material={materials.Ceiling} position={[-2.691, -0.776, -2.678]} rotation={[-Math.PI / 2, 0, 0]} scale={48.593} />
      <mesh castShadow receiveShadow geometry={nodes.Floor_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={48.593} />
      <mesh castShadow receiveShadow geometry={nodes.Wall_backwall_0.geometry} material={materials.backwall} rotation={[-Math.PI / 2, 0, 0]} scale={48.593} />
      <mesh castShadow receiveShadow geometry={nodes.Rug_Material003_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[42.924, 48.593, 48.593]} />
      <mesh castShadow receiveShadow geometry={nodes.Door_Material007_0.geometry} material={materials['Material.007']} scale={190.455} />
      <mesh castShadow receiveShadow geometry={nodes.DoorGlass_Material008_0.geometry} material={materials['Material.008']} scale={105.199} />
      <mesh castShadow receiveShadow geometry={nodes.Podium_Cube027_Podiums_0.geometry} material={materials.Podiums} position={[0, 0, 150]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_Material005_0.geometry} material={materials['Material.005']} position={[-109.308, 2.085, -97.102]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.Plane_roofthings_0.geometry} material={materials.roofthings} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.Plane001_Material010_0.geometry} material={materials['Material.010']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere_Material009_0.geometry} material={materials['Material.009']} position={[-147.661, 128.821, -469.981]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('models/room-transformed.glb')
