/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 /home/feri/Downloads/modified_supra.glb --transform --shadows 
Files: /home/feri/Downloads/modified_supra.glb [45.99MB] > modified_supra-transformed.glb [6.16MB] (87%)
Author: BRO (https://sketchfab.com/musawork786)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modified-supra-6034a755079b485ca0b284c4a0c96d1f
Title: Modified supra
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Supra(props) {
  const { nodes, materials } = useGLTF('models/modified_supra-transformed.glb')
  return (
    <group {...props} dispose={null} position-x={-4}>
      <mesh castShadow receiveShadow geometry={nodes.MKVWing_MKVBlackGloss_0.geometry} material={materials.PaletteMaterial001} position={[0, -0.021, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MKVWing_MKVPaint_0.geometry} material={materials.PaletteMaterial002} position={[0, -0.021, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MKVIntercooler_MKVBlackMatt_0.geometry} material={materials.PaletteMaterial003} position={[0, -0.021, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MKVIntercooler_MKVMetallic_0.geometry} material={materials.PaletteMaterial004} position={[0, -0.021, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MKVQuarterglassL_MKVWindow_0.geometry} material={materials.PaletteMaterial005} position={[0, -0.021, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MKVBody_MKVBadges_0.geometry} material={materials['MKV.Badges']} position={[0, 0.329, -1.294]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MKVBody_MKVCarpet_0.geometry} material={materials['MKV.Carpet']} position={[0, 0.329, -1.294]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MKVDoorL_MKVLeather_0.geometry} material={materials.PaletteMaterial006} position={[0.929, 0.558, 0.525]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MKVBacklight_MKVBrakeLight_0.geometry} material={materials.PaletteMaterial007} position={[0, -0.021, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MKVHeadlightGlassR_MKVHeadlightGlass_0.geometry} material={materials.PaletteMaterial008} position={[0, -0.021, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MKVSeatR_MKVAlcantara_0.geometry} material={materials['MKV.Alcantara']} position={[0, -0.021, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MKVHeadlightL_MKVHeadlight_0.geometry} material={materials.PaletteMaterial009} position={[0, -0.021, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.MKVWheelFtL_MKVTire_0.geometry} material={materials.PaletteMaterial010} position={[0.759, 0.33, 1.295]} rotation={[1.257, 0, 0]} scale={[0.014, 0.013, 0.013]} />
      <mesh castShadow receiveShadow geometry={nodes.MKVWheelFtL_MKVBrakeDisc_0.geometry} material={materials.PaletteMaterial011} position={[0.759, 0.33, 1.295]} rotation={[1.257, 0, 0]} scale={[0.014, 0.013, 0.013]} />
    </group>
  )
}

useGLTF.preload('models/modified_supra-transformed.glb')
